name       : libpano13
version    : 2.9.19
release    : 3
source     :
    - https://kent.dl.sourceforge.net/project/panotools/libpano13/libpano13-2.9.19/libpano13-2.9.19.tar.gz : 037357383978341dea8f572a5d2a0876c5ab0a83dffda431bd393357e91d95a8
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : libpano13 library
description: |
    Part of Panorama Tools by Helmut Dersch of the University of Applied Sciences Furtwangen.
builddeps  :
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpng)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
