name       : libpano13
version    : 2.9.21
release    : 5
source     :
    - https://sourceforge.net/projects/panotools/files/libpano13/libpano13-2.9.21/libpano13-2.9.21.tar.gz : 79e5a1452199305e2961462720ef5941152779c127c5b96fc340d2492e633590
homepage   : http://panotools.sourceforge.net/
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : libpano13 library
description: |
    Part of Panorama Tools by Helmut Dersch of the University of Applied Sciences Furtwangen.
builddeps  :
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpng)
setup      : |
    %cmake . -DSUPPORT_JAVA_PROGRAMS=0
build      : |
    %make
install    : |
    %make_install
#check      : |
    #%make test
