name       : libpano13
version    : 2.9.19
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/panotools/libpano13/libpano13-2.9.19/libpano13-2.9.19.tar.gz : 037357383978341dea8f572a5d2a0876c5ab0a83dffda431bd393357e91d95a8
license    : GPL-2.0
summary    : libpano13 library
description: |
    Part of Panorama Tools by Helmut Dersch of the University of Applied Sciences Furtwangen.
builddeps  :
    - pkgconfig(libtiff-4)
    - pkgconfig(libpng)
    - libjpeg-turbo-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
