name       : libpano13
version    : 2.9.20
release    : 4
source     :
    - https://sourceforge.net/projects/panotools/files/libpano13/libpano13-2.9.20/libpano13-2.9.20.tar.gz : 3b532836c37b8cd75cd2227fd9207f7aca3fdcbbd1cce3b9749f056a10229b89
homepage   : http://panotools.sourceforge.net/
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : libpano13 library
description: |
    Part of Panorama Tools by Helmut Dersch of the University of Applied Sciences Furtwangen.
builddeps  :
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpng)
setup      : |
    %cmake . -DSUPPORT_JAVA_PROGRAMS=0
build      : |
    %make
install    : |
    %make_install
#check      : |
    #%make test
